# Generated by Django 3.2.7 on 2021-09-15 21:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('one_api_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('height', models.CharField(max_length=100)),
                ('race', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('birth', models.CharField(max_length=100)),
                ('spouse', models.CharField(max_length=100)),
                ('death', models.CharField(max_length=100)),
                ('realm', models.CharField(max_length=100)),
                ('hair', models.CharField(max_length=100)),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('one_api_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('dialog', models.CharField(max_length=100)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote', to='movie.character')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
