# Generated by Django 3.2.7 on 2021-09-15 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='one_api_id',
            new_name='_id',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='one_api_id',
            new_name='_id',
        ),
    ]
