# Generated by Django 3.2.7 on 2021-09-16 08:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0006_favouritecharacter_favouritequote'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favouritecharacter',
            unique_together={('user', 'character')},
        ),
    ]
